### PR TITLE
Do not log warn when no data allowed

### PR DESCRIPTION
**Pull request by alenkacz**
When no data are selected I don't think the log should be full of WARN
messages

### CODE REVIEW

**Comment by scobal** [comment]
@alenkacz would be good to add a unit test for this

**Comment by alenkacz** [comment]
@scobal ha, I had a bug there - I did not want to log WARN but I wanted to do "continue" ... so I added one more commit.

Unfortunately I don't think I can unit test this since Logger is a static field...

**Comment by scobal** [comment]
@alenkacz fair enough :+1:

Up to you, but you could avoid checking value.isPresent() twice by re-writing it to this:

    if (!value.isPresent()) {
        if (!check.isAllowNoData()) {
            LOGGER.warn("No value present for {} and check must have data", target);
        }
        continue;
    }

**Comment by alenkacz** [comment]
@scobal I don't think that double check to isPresent has any performance implications but I find your code more readable so I have changed it. Thanks!

**Pull request merged**
