### PR TITLE
spring security implementation

### PR DESCRIPTION
**Pull request by asebak**
This is my continued PR from here: https://github.com/scobal/seyren/pull/282

I now implemented the security using Spring security.  I added 2 different authentication providers either using LDAP protocol or using a mongodb.  "SECURITY_ENABLED" environment variable sets whether to enable the security on the client/server side.  If it's disabled the application will function exactly as it was before.  The configurations for spring security are stored in both securityContext.xml and security.properties.  I have documented these in the Readme.md.  Here are some new screenshots using the database authentication provider which allows the admin to add users from the UI.  There's now a dropdown on the right side that shows the user's name and a logout button and if they are an admin they will see a menu item called Admin where they can manage users.

admin-dp

When a database authentication provider is used, they can add users if they do not exist.

add-user

Success message when the user was added.
user-added-success

Autocomplete textbox with the newly added user.

user-added-autocomplete

I also had my stuff looked at by @jmirc who was of the creators of the jhipster project where they implemented spring security with angular js.

### CODE REVIEW

**Comment by asebak** [comment]
@neilprosser @obazoud Can you check it out. Let me know if you have any questions

**Comment by obazoud** [comment]
Is there a way to use Mongodb to store users auth. ? I see hsqldb as dependency.

**Comment by asebak** [comment]
@obazoud Hello Olivier,
I just removed all the hibernate, sql, jdbc and jpa stuff and now storing the users in mongodb. Can you check it out.

**Comment by asebak** [comment]
@neilprosser @obazoud can you check this out, it has been updated.

**Pull request closed without merging**
