### PR TITLE
Hipchat api v2

### PR DESCRIPTION
**Pull request by rposbo**
The current update for hipchat api v2 doesn't take into account the changes to the API structure itself AFAIK; this PR is hipchat api v2 only (what with v1 being deprecated) and is tested as working with a live hipchat account.

Fixes https://github.com/scobal/seyren/issues/270

### CODE REVIEW

**Comment by asebak** [comment]
#290 fixed this issue

**Comment by rposbo** [comment]
Unfortunately not: the structure of the Hipchat API changed with v2, so the endpoints and the message structure is different. Just changing the "v" in the url isn't enough. I've validated this by running a build of the current ```master```, pointing at a live Hipchat endpoint with no success; then running a build of this PR instead works.

I could create a separate notification service for Hipchat V2 in order to leave Hipchat V1 alone, but just changing the number in the URL isn't enough to support v2 api.

Thoughts?

**Comment by asebak** [comment]
Well if v1 is deperacted might as well just support only v2.  You're right seems like #290 doesn't actually fix anything.  You might to reach directly to @obazoud.

**Comment by obazoud** [comment]
I can't automatically merge this PR, could you please rebase from master and squash your commits ?
OK to add Hipchat v2 /cc @neilprosser @scobal

**Pull request closed without merging**
