### PR TITLE
Support for Victorops Notification

### PR DESCRIPTION
**Pull request by nageshwara**
This PR is to add support for victorops to seyren. I did this by using REST API provided by victorops.

API is given here: http://victorops.force.com/knowledgebase/articles/Integration/Alert-Ingestion-API-Documentation/

### CODE REVIEW

**Comment by obazoud** [comment]
Thanks @nageshwara 

* Could you add documentation in README.md ?
* Is there any API token to add to VictorOps ? Is it in target field ? Usually, we add API token via [system property](https://github.com/scobal/seyren#config) to avoid secret data in mongodb.

**Comment by nageshwara** [comment]
Hi @obazoud,
Sorry for some reason I did not get notification about your comment. 
1) will add documentation to README. 
2) VictorOps gives an url to post to, which includes token in it. I could make it a system property.

**Comment by nageshwara** [comment]
@obazoud updated!

**Comment by obazoud** [comment]
Thanks @nageshwara !

**Pull request merged**
