### PR TITLE
security implementation

### PR DESCRIPTION
**Pull request by asebak**
Hello Seyren Team,

This is an implementation for adding security and validation.  It has only been done for subscriptions so you can set access rights to specific users.  I would love to eventually add more restrictions say to checks and things like that. By Default the authentication for client and server side is disabled and the application will function exactly as it was before.  When you enable authentication you will see a login screen like below:
seyern-loginscreen

If a user is trying to add a subscription and does not have the required permissions you will see a screen like the following:

seyren-subscriptionrestriction

There's an admin tool that allows the admin to modify users and it has an autocomplete textbox like the following:
seyren-admin-autocomplete

Once the user is selected, permissions can be set for subscriptions can be changed as follows:

seyren-admin-set-subscription-permissions

In regards to the implementation their is an authentication provider interface which in the future I will make it configurable where the user can choose what provider to authenticate(i.e local mongodb users).  Right now it validates against an ldap webservice(common protocol for active directory) where configurations and be provided and it will be a generic service.  I also added several unit tests to make sure the functionality didn't break and of the old code.

On the server side I am not managing any sessions, hence everytime a request is made the credentials are validated against the authentication provider interface.

Thanks,
Ahmad.

### CODE REVIEW

**Comment by obazoud** [comment]
Thanks @asebak.
Why not use Spring security ?

@neilprosser @scobal do you agree to add security feature in Seyren (disabled by default) ?

**Comment by asebak** [comment]
@obazoud Yeah I didn't think about that, if it's okay with @neilprosser and @scobal then I will add it.

**Comment by obazoud** [comment]
We can have a look of [jhipster project](http://jhipster.github.io/) that already have integrated AngularJS and Spring/SpringSecurity.

**Comment by jmirc** [comment]
I will help @asebak ;)

**Comment by neilprosser** [comment]
Sorry to get to this so late. I think adding security sounds like a good plan.

**Pull request closed without merging**
