### PR TITLE
adding support for multiple graphite instance

### PR DESCRIPTION
**Pull request by rnathani**
my company uses multiple graphite instances for monitoring. I believe this feature could be use by many seyren users.

### CODE REVIEW

**Comment by obazoud** [comment]
Thanks @rnathani 
Could you please the same code formatter ? Diff would be clearer.

**Comment by rnathani** [comment]
Thanks @obazoud

Sure I will format the code...do you use any specific formatter?

**Comment by zot420** [comment]
Any chance this pull request can get done, this is a huge help, as I would no longer have to run multiple instances

**Comment by scobal** [comment]
Closing as I think this has been replaced by 384

**Pull request closed without merging**
